import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '600']
});

export const metadata = {
  title: "Travel Guide Website",
  description: "Generated by Travel Guide Website",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} w-screen h-screen bg-amber-950`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
